### ISSUE TITLE
Write fail

### ISSUE THREAD

**Issue by hfiguiere** [flathub/org.raspberrypi.rpi-imager#8] opened 2020-12-27 02:29 UTC
I tried both the 1.5 on flathub and the 1.4 version as well. When I try to write an image to my SD card on the internal SD card reader, after it asked the permissions, I get this error:

![image](https://user-images.githubusercontent.com/114441/103162557-149c1b80-47c0-11eb-84db-8b956643e271.png)

I tried with a USB card reader and get the same thing albeit a different device.

I tried 1.5 from flathub on my Raspberry Pi with the same reader, same error.
I tried **1.5 from Debian/Raspberry Pi OS**, with the same reader, and it **works**.

**Comment by hfiguiere** [comment] 2020-12-27 03:26
I have managed to get it to work, not sure how, using the microSD reader over USB (it's /dev/sdX), the same way it failed.

It might be because it was insert before I started the app, but I would have to check.

**Comment by hfiguiere** [comment] 2020-12-27 03:28
I don't discount an upstream issue, but the fact that it just worked with the Debian version mad me think it could be.

**Comment by ghisvail** [comment] 2020-12-27 12:06
I have had issues in the past with permissions on this app. They are now on par with other media writing tools like the [Fedora Media Writer](https://github.com/flathub/org.fedoraproject.MediaWriter/blob/master/org.fedoraproject.MediaWriter.json) or [PopOS Popsicle](https://github.com/flathub/com.system76.Popsicle/blob/master/com.system76.Popsicle.yaml).

Have you had a chance to start the app from the cli and check whether error messages popped up when attempting a write?

**Comment by hfiguiere** [comment] 2020-12-27 14:45
yes, and no message. 

I atually only started it that way.

**Comment by ghisvail** [comment] 2021-03-19 22:03
@hfiguiere Could you try again with version 1.6?

I was able to format and prepare a USB pendrive with RetroPie and Raspberry Pi OS.

**Comment by orgcontrib** [comment] 2021-06-05 16:07
I have somwhat similar (mounting) issue on Fedora Linux 34 with v1.6.
file:///home/tux/Pictures/f34_v1.6_step1.png
file:///home/tux/Pictures/f34_v1.6_step2.png
`$ mount |g sda1
/dev/sda1 on /run/media/tux/A476-FCC5 type vfat (rw,nosuid,nodev,relatime,uid=1001,gid=1001,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,showexec,utf8,flush,errors=remount-ro,uhelper=udisks2)
`

**Comment by orgcontrib** [comment] 2021-06-06 03:09
My workaround was to do it the old fashion way.
[f34_fmw_alt.png](https://github.com/orgcontrib/screenshots/blob/master/f34_fmw_alt.png)

**Comment by Jesse-Millwood** [comment] 2021-06-23 17:44
I tried to do the Bootloader image install with v1.6 and received a message saying "error formatting (through udisks2)" almost immediately. 
However, I tried doing the RISC OS (5.28) with the same sdcard and it asked for my root password then went through the write process, verify process, and showed a success.

**Comment by Iolaum** [comment] 2021-10-16 15:15
Same error with version 1.6.2 on Fedora Silverblue 35 (beta).

**Comment by ghisvail** [comment] 2021-11-30 11:34
> Opened Flatseal and I see that the app has access to devices=all which to me means there shouldn't be any problem to access /dev

Indeed

**Comment by dhitchcock** [comment] 2022-04-08 02:52
I got this error on Fedora 35 flatpak.  Worked when I added my user to the 'disk' group

**Comment by JamesBelchamber** [comment] 2022-04-20 19:09
Same issue on Silverblue, and adding my user to the `disk` group also fixes the problem.

I have no clue how to map that to Flatpak permissions :eyes:

**Comment by joshuag1000** [comment] 2022-04-20 19:37
Just throwing ideas out but could this be an issue with the way permissions are setup on the distros you are using rather than a flatpak issue?

**Comment by Ramblurr** [comment] 2022-10-01 18:06
Also having this problem on Fedora 36 Silverblue. There is no "disk" group on my install. Permissions look similar to Fedora Media Writer, though without the dbus permissions to talk to udisks.

**Comment by jurf** [comment] 2022-11-11 17:11
Silverblue users are affected by this [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1919994).

This is the current [workaround](https://bugzilla.redhat.com/show_bug.cgi?id=1919994#c22):
```
sudo su
grep -E '^disk:' /usr/lib/group >> /etc/group
usermod -aG disk <username_here>
```

**Comment by orgcontrib** [comment] 2022-11-12 19:57
> Just throwing ideas out but could this be an issue with the way permissions are setup for a user on the distros you are using rather than a flatpak issue?

Damn right. Look [here](https://github.com/fedora-selinux/selinux-policy/issues/1449).

**Comment by faelana** [comment] 2023-01-24 20:19
Fixed after adding to `disk` group.

**Comment by ghisvail** [comment] 2023-01-24 20:29
Closing since it has been confirmed the solution is to ensure the user belongs to the `disk` group.

**Closed by ghisvail** 2023-01-24 20:29 UTC
Labels: bug, help wanted

**Comment by faelana** [comment] 2023-01-25 02:52
@ghisvail this should be added to the readme file here and the flathub description as well.
